logLevel: error
logFormat: json
clusterName: my-super-local-cluster
route:
  routes:
    - match:
        - receiver: "dump"
receivers:
  - name: "dump"
    stdout: {}
enrichEvents:
  labels: true
  annotations: true
